### PR TITLE
Add travis support

### PR DESCRIPTION
**Pull request by stefk**

### CODE REVIEW

**Comment by ngodfraind** [comment]
Is the composer.lock normal ?

**Comment by stefk** [comment]
@ngodfraind, yes. Composer's dependency resolution is heavy on memory, and travis builds have only 1Go available, so the bundle has to embed its own composer.lock (which must be updated regularly...). It's a very annoying constraint, but I don't think there's another way to solve that issue.

(BTW, still trying to fix the build failure, I'll ping you when it's mergeable)

**Comment by stefk** [comment]
> I'll ping you when it's mergeable

lol

**Comment by ngodfraind** [comment]
w/e it's not like it's going to crash anything ;)

2015-10-14 13:56 GMT+02:00 stefk <notifications@github.com>:

> I'll ping you when it's mergeable
>
> lol
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/ForumBundle/pull/77#issuecomment-148027407>.
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Pull request merged**
